# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Borders' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Borders
  pod 'RxSwift'
  pod 'RxCocoa'
  
end

target 'BordersTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxTest'
    pod 'RxBlocking'
end
